// [agreement-esign] Renders a DocuSign-style "Certificate of Completion" — the
// tamper-evident audit trail for a signed client agreement (envelope id, signer,
// SHA-256 hash, and the full sent/viewed/signed event history with IP + device).
// pdfkit (no Chromium). Returns a Buffer; bind it as the final page of the
// signed agreement PDF.
import PDFDocument from "pdfkit";

const NAVY = "#0A0E1A", MINT = "#00C9A0", INK = "#1A1917", MUTE = "#6B6860", BORDER = "#E5E2DC";

export interface AgreementEvent {
  type: "sent" | "viewed" | "signed" | "sealed" | string;
  at: string;            // ISO
  ip?: string | null;
  userAgent?: string | null;
  email?: string | null;
  by?: string | null;    // office user, for 'sent'
}
export interface AgreementCertData {
  companyName: string;
  agreementTitle: string;
  envelopeId: string;
  signerName?: string | null;
  signerEmail?: string | null;
  status: string;
  contentHash: string;
  verifyUrl?: string | null;
  consent: boolean;
  events: AgreementEvent[];
}

const fmt = (iso: string) => {
  try { return new Date(iso).toLocaleString("en-US", { month: "short", day: "numeric", year: "numeric", hour: "numeric", minute: "2-digit" }); }
  catch { return iso; }
};
const EVENT_LABEL: Record<string, string> = {
  sent: "Sent for signature", viewed: "Viewed by signer", signed: "Signed", sealed: "Sealed — document locked",
};

export function renderAgreementCertificate(data: AgreementCertData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: "LETTER" });
    const chunks: Buffer[] = [];
    doc.on("data", (c) => chunks.push(c as Buffer));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const left = 50, right = doc.page.width - 50, width = right - left;

    // Header
    doc.rect(0, 0, doc.page.width, 70).fill(NAVY);
    doc.fillColor("#FFFFFF").fontSize(15).font("Helvetica-Bold").text("Certificate of Completion", left, 22);
    doc.fillColor("#9CA3AF").fontSize(10).font("Helvetica").text(data.agreementTitle, left, 44, { width: width - 120 });
    doc.fillColor(MINT).fontSize(10).font("Helvetica-Bold").text(String(data.status || "").toUpperCase(), right - 120, 30, { width: 120, align: "right" });

    let y = 90;
    const row = (label: string, value: string, mono = false) => {
      doc.fillColor(MUTE).fontSize(9).font("Helvetica").text(label, left, y);
      doc.fillColor(INK).fontSize(11).font(mono ? "Courier" : "Helvetica").text(value || "—", left, y + 12, { width });
      y = doc.y + 10;
    };
    row("Envelope ID", data.envelopeId, true);
    row("Document hash (SHA-256) · tamper-evident", data.contentHash, true);
    row("Signer", data.signerName || "—");
    row("Signer email", data.signerEmail || "—");

    y += 4;
    doc.moveTo(left, y).lineTo(right, y).strokeColor(BORDER).stroke();
    y += 14;
    doc.fillColor(MUTE).fontSize(9).font("Helvetica-Bold").text("EVENT HISTORY", left, y, { characterSpacing: 0.5 });
    y += 16;
    for (const e of data.events) {
      doc.fillColor(MINT).fontSize(11).font("Helvetica-Bold");
      // small marker dot
      doc.circle(left + 3, y + 5, 2.5).fill(MINT);
      doc.fillColor(INK).fontSize(10.5).font("Helvetica-Bold").text(EVENT_LABEL[e.type] || e.type, left + 14, y);
      y = doc.y;
      const meta = [fmt(e.at), e.email || null, e.ip ? `IP ${e.ip}` : null, e.userAgent || null, e.by ? `by ${e.by}` : null].filter(Boolean).join("  ·  ");
      doc.fillColor(MUTE).fontSize(9).font("Helvetica").text(meta, left + 14, y, { width: width - 14 });
      y = doc.y + 9;
    }

    y += 6;
    doc.moveTo(left, y).lineTo(right, y).strokeColor(BORDER).stroke();
    y += 12;
    doc.fillColor("#374151").fontSize(9).font("Helvetica").text(
      `${data.consent ? "The signer consented to use electronic records and signatures (ESIGN/UETA). " : ""}` +
      `This certificate is generated by ${data.companyName} via Qleno and bound to the signed document above; any change to the document produces a different hash.` +
      (data.verifyUrl ? ` Verify at ${data.verifyUrl}` : ""),
      left, y, { width, lineGap: 2 },
    );

    doc.end();
  });
}
