import PDFDocument from "pdfkit";
import fs from "fs";
import path from "path";

interface AgreementPdfData {
  submissionId: number;
  formName: string;
  companyName: string;
  termsBody: string;
  responses: Record<string, string>;
  signatureName: string;
  signedAt: string;
  ipAddress: string;
  contentHash: string;
}

export async function generateAgreementPdf(data: AgreementPdfData): Promise<string> {
  const pdfsDir = process.env.PDFS_DIR || path.resolve(process.cwd(), "pdfs");
  if (!fs.existsSync(pdfsDir)) {
    fs.mkdirSync(pdfsDir, { recursive: true });
  }

  const filename = `agreement-${data.submissionId}-${Date.now()}.pdf`;
  const filepath = path.join(pdfsDir, filename);

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 60, size: "LETTER" });
    const stream = fs.createWriteStream(filepath);
    doc.pipe(stream);

    const brand = "#5B9BD5";
    const dark = "#1A1917";
    const gray = "#6B7280";
    const light = "#E5E2DC";
    const pageWidth = doc.page.width - 120;

    doc.rect(0, 0, doc.page.width, 72).fill(brand);
    doc.fillColor("#FFFFFF").fontSize(20).font("Helvetica-Bold")
      .text(data.companyName, 60, 20, { width: doc.page.width - 120 });
    doc.fontSize(10).font("Helvetica")
      .text(data.formName, 60, 46, { width: doc.page.width - 120 });
    doc.fillColor(gray).fontSize(9).font("Helvetica")
      .text(`Signed: ${data.signedAt}`, doc.page.width - 200, 46, { width: 140, align: "right" });

    let y = 95;

    const sectionHeader = (title: string) => {
      doc.rect(60, y, pageWidth, 22).fill("#F7F6F3");
      doc.fillColor(brand).fontSize(10).font("Helvetica-Bold")
        .text(title.toUpperCase(), 68, y + 6, { width: pageWidth - 16 });
      y += 30;
    };

    const paragraph = (text: string) => {
      if (!text) return;
      doc.fillColor(dark).fontSize(9.5).font("Helvetica")
        .text(text, 60, y, { width: pageWidth, lineGap: 2 });
      y += doc.heightOfString(text, { width: pageWidth, lineGap: 2 }) + 12;
    };

    const addPageIfNeeded = (spaceNeeded = 80) => {
      if (y + spaceNeeded > doc.page.height - 80) {
        doc.addPage();
        y = 60;
      }
    };

    const clientResponses = Object.entries(data.responses);
    if (clientResponses.length > 0) {
      sectionHeader("Client Information");
      clientResponses.forEach(([key, value]) => {
        if (!value) return;
        const label = key.replace(/_/g, " ").replace(/\b\w/g, c => c.toUpperCase());
        doc.fillColor(gray).fontSize(8).font("Helvetica-Bold").text(label.toUpperCase(), 60, y);
        doc.fillColor(dark).fontSize(10).font("Helvetica").text(String(value), 220, y - 1);
        y += 20;
      });
      y += 10;
    }

    if (data.termsBody) {
      const sections = data.termsBody.split(/\n\n+/);
      sections.forEach((section) => {
        const lines = section.trim().split("\n");
        const possibleHeader = lines[0];
        const isHeader = possibleHeader === possibleHeader.toUpperCase() && possibleHeader.length < 80 && lines.length > 1;

        addPageIfNeeded(60);

        if (isHeader) {
          sectionHeader(possibleHeader);
          const rest = lines.slice(1).join("\n").trim();
          if (rest) paragraph(rest);
        } else {
          paragraph(section.trim());
        }
      });
    }

    addPageIfNeeded(120);
    doc.moveTo(60, y).lineTo(doc.page.width - 60, y).strokeColor(light).stroke();
    y += 20;

    sectionHeader("Electronic Signature Record");

    doc.fillColor(dark).fontSize(14).font("Helvetica-Bold")
      .text(data.signatureName, 60, y, { width: pageWidth });
    y += 22;
    doc.fillColor(gray).fontSize(8).font("Helvetica")
      .text("TYPED NAME (ELECTRONIC SIGNATURE)", 60, y);
    y += 18;

    const sigFields: [string, string][] = [
      ["Signed By", data.signatureName],
      ["Date & Time", data.signedAt],
      ["IP Address", data.ipAddress],
      ["Document Hash (SHA-256)", data.contentHash],
    ];
    sigFields.forEach(([label, value]) => {
      doc.fillColor(gray).fontSize(8).font("Helvetica-Bold").text(label.toUpperCase(), 60, y);
      doc.fillColor(dark).fontSize(9).font("Helvetica").text(value, 220, y - 1, { width: pageWidth - 160 });
      y += 18;
    });

    y += 8;
    doc.fontSize(8).fillColor(gray).font("Helvetica")
      .text(
        "This document constitutes a legally binding electronic signature in accordance with the Electronic Signatures in Global and National Commerce Act (E-SIGN) and the Uniform Electronic Transactions Act (UETA).",
        60, y, { width: pageWidth, lineGap: 2 }
      );

    const pageCount = (doc as any)._pageBuffer?.length || 1;
    for (let i = 0; i < pageCount; i++) {
      doc.switchToPage(i);
      doc.fillColor(gray).fontSize(7).font("Helvetica")
        .text(
          `${data.companyName} — ${data.formName} — Generated by CleanOps Pro — Page ${i + 1}`,
          60, doc.page.height - 30, { width: pageWidth, align: "center" }
        );
    }

    doc.end();
    stream.on("finish", () => resolve(`/api/pdfs/${filename}`));
    stream.on("error", reject);
  });
}
