// [help-guides 2026-06-25] Tech guide CONTENT — single source of truth for the
// in-app Help & Guides center (field-technician audience). Plain-English +
// Spanish, one screenshot + caption per step. This file is the authored content;
// runGuidesMigration() upserts each entry into the `guides` table at boot
// (ON CONFLICT (slug) DO UPDATE), so editing wording here and redeploying
// refreshes the live guides — no other code change needed.
//
// Screenshots: each step's `image` is the FINAL committed path
// (/guides/<slug>/step-N.png). Placeholder PNGs ship at those paths today; the
// capture session just overwrites the files in place — no content edit required.
//
// Icons must be a name present in the ICONS map in pages/help.tsx (lucide).

export type GuideContentStep = {
  order: number;
  image: string;
  caption_en: string;
  caption_es: string;
};

export type GuideContent = {
  slug: string;
  audience: "tech" | "office" | "all";
  category: string;
  icon: string;
  sort_order: number;
  title_en: string;
  title_es: string;
  summary_en: string;
  summary_es: string;
  steps: GuideContentStep[];
};

const step = (
  slug: string,
  order: number,
  caption_en: string,
  caption_es: string,
): GuideContentStep => ({
  order,
  image: `/guides/${slug}/step-${order}.png`,
  caption_en,
  caption_es,
});

export const TECH_GUIDES: GuideContent[] = [
  {
    slug: "getting-started-tech",
    audience: "tech",
    category: "Getting started",
    icon: "Smartphone",
    sort_order: 1,
    title_en: "Getting started on your phone",
    title_es: "Empezando en tu teléfono",
    summary_en: "Log in and find your way around the app.",
    summary_es: "Inicia sesión y aprende a moverte por la app.",
    steps: [
      step("getting-started-tech", 1,
        "Open the app and log in with the email and password the office gave you.",
        "Abre la app e inicia sesión con el correo y la contraseña que te dio la oficina."),
      step("getting-started-tech", 2,
        "The bar at the bottom is your menu: Dashboard, My Jobs, and More.",
        "La barra de abajo es tu menú: Inicio, Mis Trabajos y Más."),
      step("getting-started-tech", 3,
        "Tap My Jobs to see your work for the day.",
        "Toca Mis Trabajos para ver tu trabajo del día."),
      step("getting-started-tech", 4,
        "Tap More for guides, time off, and your account.",
        "Toca Más para ver guías, tiempo libre y tu cuenta."),
    ],
  },
  {
    slug: "my-day-jobs",
    audience: "tech",
    category: "Your day",
    icon: "Briefcase",
    sort_order: 2,
    title_en: "See your jobs for the day",
    title_es: "Ver tus trabajos del día",
    summary_en: "Your assigned houses, in the order you'll do them.",
    summary_es: "Tus casas asignadas, en el orden que las harás.",
    steps: [
      step("my-day-jobs", 1,
        "Open My Jobs. Each card is one house, listed by time from top to bottom.",
        "Abre Mis Trabajos. Cada tarjeta es una casa, ordenada por hora de arriba a abajo."),
      step("my-day-jobs", 2,
        "The colored bar on a card shows that job's status at a glance.",
        "La barra de color en la tarjeta muestra el estado del trabajo de un vistazo."),
      step("my-day-jobs", 3,
        "Pull down to refresh if the office just added or changed a job.",
        "Desliza hacia abajo para actualizar si la oficina acaba de agregar o cambiar un trabajo."),
      step("my-day-jobs", 4,
        "Tap any card to open the full job.",
        "Toca cualquier tarjeta para abrir el trabajo completo."),
    ],
  },
  {
    slug: "job-details",
    audience: "tech",
    category: "At the house",
    icon: "FileText",
    sort_order: 3,
    title_en: "Open a job's details",
    title_es: "Abrir los detalles de un trabajo",
    summary_en: "Address, directions, and what the customer wants.",
    summary_es: "Dirección, indicaciones y lo que quiere el cliente.",
    steps: [
      step("job-details", 1,
        "Tap a job from My Jobs to open it.",
        "Toca un trabajo en Mis Trabajos para abrirlo."),
      step("job-details", 2,
        "Tap the address or the map photo to get driving directions.",
        "Toca la dirección o la foto del mapa para obtener indicaciones para conducir."),
      step("job-details", 3,
        "Read the customer notes — how to get in, pets, and special requests.",
        "Lee las notas del cliente — cómo entrar, mascotas y pedidos especiales."),
      step("job-details", 4,
        "Check the list to see what to clean at this home.",
        "Revisa la lista para ver qué limpiar en esta casa."),
    ],
  },
  {
    slug: "on-my-way",
    audience: "tech",
    category: "At the house",
    icon: "Navigation",
    sort_order: 4,
    title_en: "Mark \"On my way\"",
    title_es: "Marcar \"En camino\"",
    summary_en: "Let the office and customer know you're driving over.",
    summary_es: "Avisa a la oficina y al cliente que vas en camino.",
    steps: [
      step("on-my-way", 1,
        "When you leave for the next house, open that job.",
        "Cuando salgas hacia la próxima casa, abre ese trabajo."),
      step("on-my-way", 2,
        "Tap On My Way.",
        "Toca En camino."),
      step("on-my-way", 3,
        "Only tap it when you're actually leaving — this is what tracks your drive between houses.",
        "Tócalo solo cuando realmente salgas — esto es lo que registra tu manejo entre casas."),
    ],
  },
  {
    slug: "clock-in-out",
    audience: "tech",
    category: "At the house",
    icon: "Clock",
    sort_order: 5,
    title_en: "Clock in and out at each house",
    title_es: "Registrar entrada y salida en cada casa",
    summary_en: "Start the timer when you arrive, stop it when you finish.",
    summary_es: "Inicia el temporizador al llegar y detenlo al terminar.",
    steps: [
      step("clock-in-out", 1,
        "When you arrive, open the job and tap Clock In.",
        "Cuando llegues, abre el trabajo y toca Registrar entrada."),
      step("clock-in-out", 2,
        "Clean the home. The timer runs while you work.",
        "Limpia la casa. El temporizador corre mientras trabajas."),
      step("clock-in-out", 3,
        "When you finish, tap Clock Out.",
        "Cuando termines, toca Registrar salida."),
      step("clock-in-out", 4,
        "Do this at every house — there is no separate start- or end-of-day button.",
        "Hazlo en cada casa — no hay un botón aparte para empezar o terminar el día."),
    ],
  },
  {
    slug: "add-photos",
    audience: "tech",
    category: "At the house",
    icon: "Camera",
    sort_order: 6,
    title_en: "Add before & after photos",
    title_es: "Agregar fotos de antes y después",
    summary_en: "Photos protect you and show your work.",
    summary_es: "Las fotos te protegen y muestran tu trabajo.",
    steps: [
      step("add-photos", 1,
        "Open the job and tap the camera button.",
        "Abre el trabajo y toca el botón de cámara."),
      step("add-photos", 2,
        "Take \"before\" photos when you arrive.",
        "Toma fotos de \"antes\" cuando llegues."),
      step("add-photos", 3,
        "Take \"after\" photos as you finish each room.",
        "Toma fotos de \"después\" a medida que terminas cada cuarto."),
      step("add-photos", 4,
        "Photos upload on their own — even on a slow signal.",
        "Las fotos se suben solas — incluso con señal lenta."),
    ],
  },
  {
    slug: "customer-not-home",
    audience: "tech",
    category: "At the house",
    icon: "UserX",
    sort_order: 7,
    title_en: "Customer isn't home",
    title_es: "El cliente no está",
    summary_en: "What to do when no one answers the door.",
    summary_es: "Qué hacer cuando nadie abre la puerta.",
    steps: [
      step("customer-not-home", 1,
        "Knock, ring the bell, and wait at the door.",
        "Toca la puerta, llama al timbre y espera en la entrada."),
      step("customer-not-home", 2,
        "Call the customer and the office from the job screen.",
        "Llama al cliente y a la oficina desde la pantalla del trabajo."),
      step("customer-not-home", 3,
        "Wait the full time the office tells you before leaving.",
        "Espera el tiempo completo que indique la oficina antes de irte."),
      step("customer-not-home", 4,
        "If no one comes, tap No Show so the office knows what happened.",
        "Si nadie llega, toca No se presentó para que la oficina sepa qué pasó."),
    ],
  },
  {
    slug: "understand-your-pay",
    audience: "tech",
    category: "Your pay",
    icon: "DollarSign",
    sort_order: 8,
    title_en: "Understand your pay",
    title_es: "Entiende tu pago",
    summary_en: "How your earnings are figured for each job.",
    summary_es: "Cómo se calculan tus ganancias en cada trabajo.",
    steps: [
      step("understand-your-pay", 1,
        "House cleans pay a commission — a share of the job's price.",
        "Las limpiezas de casa pagan comisión — una parte del precio del trabajo."),
      step("understand-your-pay", 2,
        "When two of you clean a home, the pay splits by the time each one works.",
        "Cuando dos limpian una casa, el pago se reparte por el tiempo que trabaja cada uno."),
      step("understand-your-pay", 3,
        "Hours on the screen are for records — you're paid by commission, not by the hour.",
        "Las horas en la pantalla son para registro — te pagan por comisión, no por hora."),
      step("understand-your-pay", 4,
        "\"Allowed hours\" is the time budget for a job — finishing under it makes you more effective.",
        "Las \"horas permitidas\" son el presupuesto de tiempo del trabajo — terminar antes te hace más eficiente."),
    ],
  },
  {
    slug: "mileage",
    audience: "tech",
    category: "Your pay",
    icon: "MapPin",
    sort_order: 9,
    title_en: "How mileage works",
    title_es: "Cómo funciona el millaje",
    summary_en: "Driving between houses is paid back to you.",
    summary_es: "El manejo entre casas se te reembolsa.",
    steps: [
      step("mileage", 1,
        "Mileage is the drive from one customer's house to the next.",
        "El millaje es el manejo de la casa de un cliente a la siguiente."),
      step("mileage", 2,
        "It's figured automatically — you never type in miles.",
        "Se calcula automáticamente — nunca escribes las millas."),
      step("mileage", 3,
        "The drive from home to your first job, and from your last job home, is not paid.",
        "El manejo de tu casa al primer trabajo, y del último trabajo a tu casa, no se paga."),
      step("mileage", 4,
        "Tapping On My Way at each house is what records the drive.",
        "Tocar En camino en cada casa es lo que registra el manejo."),
    ],
  },
  {
    slug: "request-time-off",
    audience: "tech",
    category: "Time off & alerts",
    icon: "CalendarOff",
    sort_order: 10,
    title_en: "Request time off",
    title_es: "Solicitar tiempo libre",
    summary_en: "Ask the office for a day off from your phone.",
    summary_es: "Pide un día libre a la oficina desde tu teléfono.",
    steps: [
      step("request-time-off", 1,
        "Tap More, then Time Off.",
        "Toca Más y luego Tiempo libre."),
      step("request-time-off", 2,
        "Tap Request and pick your dates.",
        "Toca Solicitar y elige tus fechas."),
      step("request-time-off", 3,
        "Add a reason if you'd like, then send it.",
        "Agrega un motivo si quieres y envíalo."),
      step("request-time-off", 4,
        "The office reviews it — you'll see it here when it's approved.",
        "La oficina la revisa — la verás aquí cuando se apruebe."),
    ],
  },
  {
    slug: "turn-on-alerts",
    audience: "tech",
    category: "Time off & alerts",
    icon: "Bell",
    sort_order: 11,
    title_en: "Turn on job alerts",
    title_es: "Activar avisos de trabajos",
    summary_en: "Get a notification when your schedule changes.",
    summary_es: "Recibe un aviso cuando cambia tu horario.",
    steps: [
      step("turn-on-alerts", 1,
        "Tap the bell, or open More and then Notification settings.",
        "Toca la campana, o abre Más y luego Ajustes de notificaciones."),
      step("turn-on-alerts", 2,
        "Tap Turn on job alerts and allow notifications when your phone asks.",
        "Toca Activar avisos de trabajos y permite las notificaciones cuando tu teléfono lo pida."),
      step("turn-on-alerts", 3,
        "Now you'll know right away when a job is added or moved.",
        "Ahora sabrás de inmediato cuando se agregue o se mueva un trabajo."),
    ],
  },
  {
    slug: "account-language",
    audience: "tech",
    category: "Account",
    icon: "KeyRound",
    sort_order: 12,
    title_en: "Password & language",
    title_es: "Contraseña e idioma",
    summary_en: "Change your password or switch English / Spanish.",
    summary_es: "Cambia tu contraseña o cambia entre inglés y español.",
    steps: [
      step("account-language", 1,
        "Tap More to find your account options.",
        "Toca Más para ver las opciones de tu cuenta."),
      step("account-language", 2,
        "Tap Change Password to set a new one.",
        "Toca Cambiar contraseña para poner una nueva."),
      step("account-language", 3,
        "Use the EN / ES switch at the top of a guide to read it in your language.",
        "Usa el botón EN / ES arriba de una guía para leerla en tu idioma."),
    ],
  },
];
