import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import branchesRouter from "./branches.js";
import companiesRouter from "./companies.js";
import usersRouter from "./users.js";
import employeeExtendedRouter from "./employee-extended.js";
import clientsRouter from "./clients.js";
import jobsRouter from "./jobs.js";
import timeclockRouter from "./timeclock.js";
import invoicesRouter from "./invoices.js";
import scorecardsRouter from "./scorecards.js";
import payrollRouter from "./payroll.js";
import loyaltyRouter from "./loyalty.js";
import dashboardRouter from "./dashboard.js";
import adminRouter from "./admin.js";
import discountsRouter from "./discounts.js";
import dispatchRouter from "./dispatch.js";
import portalRouter from "./portal.js";
import searchRouter from "./search.js";
import messagesRouter from "./messages.js";
import reportsRouter from "./reports.js";
import notificationsRouter from "./notifications.js";
import jobSmsRouter from "./job-sms.js";
import quotesRouter from "./quotes.js";
import paymentsRouter from "./payments.js";
import attachmentsRouter from "./attachments.js";
import propertyGroupsRouter from "./property-groups.js";
import agreementTemplatesRouter from "./agreement-templates.js";
import billingRouter from "./billing.js";
import formTemplatesRouter from "./form-templates.js";
import signRouter from "./sign.js";
import quoteScopesRouter from "./quote-scopes.js";
import closeDayRouter from "./close-day.js";
import paymentLinksRouter from "./payment-links.js";
import zonesRouter from "./zones.js";
import recurringRouter from "./recurring.js";
import cancellationRouter from "./cancellation.js";
import commLogRouter from "./communication-log.js";
import incentivesRouter from "./incentives.js";
import satisfactionRouter from "./satisfaction.js";
import churnRouter from "./churn.js";
import retentionRouter from "./retention.js";
import addonsRouter from "./addons.js";
import routeSequencesRouter from "./route-sequences.js";
import suppliesRouter from "./supplies.js";
import revenueGoalRouter from "./revenue-goal.js";
import policyRouter from "./policy.js";
import hrAttendanceRouter from "./hr-attendance.js";
import hrDisciplineRouter from "./hr-discipline.js";
import hrLeaveRouter from "./hr-leave.js";
import hrQualityRouter from "./hr-quality.js";
import accountsRouter from "./accounts.js";
import documentTemplatesRouter from "./document-templates.js";
import documentRequestsRouter from "./document-requests.js";
import mileageRequestsRouter from "./mileage-requests.js";
import pricingRouter from "./pricing.js";
import publicRouter from "./public.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/companies", companiesRouter);
router.use("/users", employeeExtendedRouter);
router.use("/users", usersRouter);
router.use("/clients", clientsRouter);
router.use("/jobs", jobsRouter);
router.use("/jobs", jobSmsRouter);
router.use("/timeclock", timeclockRouter);
router.use("/invoices", invoicesRouter);
router.use("/scorecards", scorecardsRouter);
router.use("/payroll", payrollRouter);
router.use("/loyalty", loyaltyRouter);
router.use("/dashboard", dashboardRouter);
router.use("/admin", adminRouter);
router.use("/discounts", discountsRouter);
router.use("/dispatch", dispatchRouter);
router.use("/portal", portalRouter);
router.use("/search", searchRouter);
router.use("/messages", messagesRouter);
router.use("/reports", reportsRouter);
router.use("/notifications", notificationsRouter);
router.use("/quotes", quotesRouter);
router.use("/payments", paymentsRouter);
router.use("/attachments", attachmentsRouter);
router.use("/property-groups", propertyGroupsRouter);
router.use("/agreement-templates", agreementTemplatesRouter);
router.use("/billing", billingRouter);
router.use("/form-templates", formTemplatesRouter);
router.use("/sign", signRouter);
router.use("/quote-scopes", quoteScopesRouter);
router.use("/close-day", closeDayRouter);
router.use("/payment-links", paymentLinksRouter);
router.use("/zones", zonesRouter);
router.use("/recurring", recurringRouter);
router.use("/cancellations", cancellationRouter);
router.use("/comms", commLogRouter);
router.use("/incentives", incentivesRouter);
router.use("/satisfaction", satisfactionRouter);
router.use("/churn", churnRouter);
router.use("/retention", retentionRouter);
router.use("/addons", addonsRouter);
router.use("/routes", routeSequencesRouter);
router.use("/supplies", suppliesRouter);
router.use("/revenue-goal", revenueGoalRouter);
router.use("/policy", policyRouter);
router.use("/hr-attendance", hrAttendanceRouter);
router.use("/hr-discipline", hrDisciplineRouter);
router.use("/hr-leave", hrLeaveRouter);
router.use("/hr-quality", hrQualityRouter);
router.use("/accounts", accountsRouter);
router.use("/branches", branchesRouter);
router.use("/document-templates", documentTemplatesRouter);
router.use("/document-requests", documentRequestsRouter);
router.use("/mileage-requests", mileageRequestsRouter);
router.use("/pricing", pricingRouter);
router.use("/public", publicRouter);

export default router;
