import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import companiesRouter from "./companies.js";
import usersRouter from "./users.js";
import employeeExtendedRouter from "./employee-extended.js";
import clientsRouter from "./clients.js";
import jobsRouter from "./jobs.js";
import timeclockRouter from "./timeclock.js";
import invoicesRouter from "./invoices.js";
import scorecardsRouter from "./scorecards.js";
import payrollRouter from "./payroll.js";
import loyaltyRouter from "./loyalty.js";
import dashboardRouter from "./dashboard.js";
import adminRouter from "./admin.js";
import discountsRouter from "./discounts.js";
import dispatchRouter from "./dispatch.js";
import portalRouter from "./portal.js";
import searchRouter from "./search.js";
import messagesRouter from "./messages.js";
import reportsRouter from "./reports.js";
import notificationsRouter from "./notifications.js";
import jobSmsRouter from "./job-sms.js";
import quotesRouter from "./quotes.js";
import paymentsRouter from "./payments.js";
import attachmentsRouter from "./attachments.js";
import propertyGroupsRouter from "./property-groups.js";
import agreementTemplatesRouter from "./agreement-templates.js";
import billingRouter from "./billing.js";
import formTemplatesRouter from "./form-templates.js";
import signRouter from "./sign.js";
import quoteScopesRouter from "./quote-scopes.js";
import closeDayRouter from "./close-day.js";
import paymentLinksRouter from "./payment-links.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/companies", companiesRouter);
router.use("/users", employeeExtendedRouter);
router.use("/users", usersRouter);
router.use("/clients", clientsRouter);
router.use("/jobs", jobsRouter);
router.use("/jobs", jobSmsRouter);
router.use("/timeclock", timeclockRouter);
router.use("/invoices", invoicesRouter);
router.use("/scorecards", scorecardsRouter);
router.use("/payroll", payrollRouter);
router.use("/loyalty", loyaltyRouter);
router.use("/dashboard", dashboardRouter);
router.use("/admin", adminRouter);
router.use("/discounts", discountsRouter);
router.use("/dispatch", dispatchRouter);
router.use("/portal", portalRouter);
router.use("/search", searchRouter);
router.use("/messages", messagesRouter);
router.use("/reports", reportsRouter);
router.use("/notifications", notificationsRouter);
router.use("/quotes", quotesRouter);
router.use("/payments", paymentsRouter);
router.use("/attachments", attachmentsRouter);
router.use("/property-groups", propertyGroupsRouter);
router.use("/agreement-templates", agreementTemplatesRouter);
router.use("/billing", billingRouter);
router.use("/form-templates", formTemplatesRouter);
router.use("/sign", signRouter);
router.use("/quote-scopes", quoteScopesRouter);
router.use("/close-day", closeDayRouter);
router.use("/payment-links", paymentLinksRouter);

export default router;
